AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  addressgeofunc

  Sample SAM Template for addressgeofunc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AddressGeoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 900
      CodeUri: address_geo/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        AddressGeo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /addresspost
            Method: get


  
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AddressGeoApi:
    Description: "API Gateway endpoint URL for Prod stage for address geolocator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/addresspost/"
  
  AddressGeoFunction:
    Description: "address geolocator Lambda Function ARN"
    Value: !GetAtt AddressGeoFunction.Arn
  AddressGeoFunctionIamRole:
    Description: "Implicit IAM Role created for address geolocator function"
    Value: !GetAtt AddressGeoFunctionRole.Arn

